### ISSUE TITLE
REGON checksum error

### ISSUE THREAD

**Issue by mrcnpdlk** [kiczort/polish-validator#2]
Sami swoi, więc napiszę w ojczystym.
Przy sprawdzaniu sumy kontrolnej REGON należy uwzględnić fakt, iż czasem suma kontrolna może wynieść 10 - bierzemy wtedy do dalszych wyliczeń samo 0. Uwzględniłbym to podczas sprawdzania i zamiast 
https://github.com/kiczort/polish-validator/blob/dd1a6db524ff52e77e9c294a6bcdf71458d087d1/src/Kiczort/PolishValidator/RegonValidator.php#L51
napisałbym
`
return $checksum % 10 == $chars[8];
`
Oczywiście podobnie dla sprawdzania REGON14
https://github.com/kiczort/polish-validator/blob/dd1a6db524ff52e77e9c294a6bcdf71458d087d1/src/Kiczort/PolishValidator/RegonValidator.php#L67

**Comment by mleczakm** [comment]
Poprawiłem w wersji 1.1.1, dodałem obejmujące ten przypadek testy.
