### ISSUE TITLE
Improper REGON validation

### ISSUE THREAD

**Issue by kmbt** [kiczort/polish-validator#4]
Witam

Walidacja 14-cyfrowego numeru REGON wymaga wykonania dwóch przebiegów - pierwszy raz z użyciem 9-ciu cyfr, a drugi raz z użyciem całego numeru (ze względu na piątą cyfrę, której waga w 14-cyfrowym wariancie obliczeń wynosi zero). Proszę uprzejmie zerknąć tutaj:  https://pl.wikipedia.org/wiki/REGON#14-cyfrowy_REGON 

W obecnej postaci algorytmu, jako piątą cyfrę, podstawić można dowolną i numer uznawany jest za poprawny. Warto to poprawić. Pozdrawiam serdecznie :)

**Comment by mleczakm** [comment]
Lepiej późno niż wcale - poprawione :) Dzięki!
